export type Prediction = {
  id: number;
  saved_at: string;
  game_date: string | null;
  season_type: string | null;
  home_team: string | null;
  away_team: string | null;
  home_starter: string | null;
  away_starter: string | null;
  home_win_pct: number | null;
  away_win_pct: number | null;
  ou_line: string | null;
  ou_prediction: string | null;
  ou_confidence: string | null;
  ou_over_pct: number | null;
  ou_risk_level: string | null;
  ou_bet_eligible: boolean | null;
  ou_bet_size: string | null;
  confidence_score: number | null;
  gvi: number | null;
  home_tms: number | null;
  away_tms: number | null;
  home_pms: number | null;
  away_pms: number | null;
  betting_recommendation: string | null;
  key_driver: string | null;
  reasoning: string | null;
  export_string: string | null;
  actual_home_score: number | null;
  actual_away_score: number | null;
  actual_total: number | null;
  ml_result: string | null;
  ou_result: string | null;
  ml_correct: number | null;
  ou_correct: number | null;
  notes: string | null;
};

export type FlagStat = {
  code: string;
  label: string;
  desc: string;
  type: 'rule' | 'pattern' | 'flag';
  triggered: number;
  ml_graded: number;
  ml_accuracy: number | null;
  ou_graded: number;
  ou_accuracy: number | null;
  expected_ml: number | null;
  expected_ou: number | null;
};

export type PatternData = {
  overall:      { total: number; graded: number; ml_wins: number; ou_graded: number; ou_wins: number };
  byConfidence: { bucket: string; total: number; ml_wins: number }[];
  byLineRange:  { line_range: string; ou_prediction: string; total: number; ou_wins: number }[];
  byWP:         { wp_bucket: string; total: number; ml_wins: number }[];
  byDirection:  { ou_prediction: string; total: number; ou_wins: number }[];
  byOUTier:     { ou_confidence: string; total: number; ou_wins: number }[];
  byMonth:      { month: string; total: number; ml_wins: number; ou_graded: number; ou_wins: number }[];
  homeAway:     { pick: string; total: number; wins: number }[];
  trend:        { ml_correct: number; ou_correct: number }[];
  totalDist:    { range: string; cnt: number }[];
};

export type Stats = {
  total: number;
  graded: number;
  ml_accuracy: number;
  ml_wins: number;
  ml_losses: number;
  ou_graded: number;
  ou_accuracy: number;
  ou_wins: number;
  ou_losses: number;
  last5_ml: number;
  last10_ml: number;
  last5_ou: number;
  last10_ou: number;
};
