export type Prediction = {
  id: number;
  saved_at: string;
  game_date: string | null;
  season_type: string | null;
  home_team: string | null;
  away_team: string | null;
  home_starter: string | null;
  away_starter: string | null;
  home_win_pct: number | null;
  away_win_pct: number | null;
  ou_line: string | null;
  ou_prediction: string | null;
  ou_confidence: string | null;
  ou_over_pct: number | null;
  confidence_score: number | null;
  gvi: number | null;
  home_tms: number | null;
  away_tms: number | null;
  home_pms: number | null;
  away_pms: number | null;
  betting_recommendation: string | null;
  key_driver: string | null;
  reasoning: string | null;
  export_string: string | null;
  actual_home_score: number | null;
  actual_away_score: number | null;
  actual_total: number | null;
  ml_result: string | null;
  ou_result: string | null;
  ml_correct: number | null;
  ou_correct: number | null;
  notes: string | null;
};

export type Stats = {
  total: number;
  graded: number;
  ml_accuracy: number;
  ml_wins: number;
  ml_losses: number;
  ou_graded: number;
  ou_accuracy: number;
  ou_wins: number;
  ou_losses: number;
  last5_ml: number;
  last10_ml: number;
  last5_ou: number;
  last10_ou: number;
};
